apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-api
  template:
    metadata:
      labels:
        app: status-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: status-api
        image: status-api:1.0
        ports:
        - containerPort: 8080
